spring:
  application:
    name: Barbershop

  datasource:
    url: jdbc:mysql://localhost:3306/barbershopdb
    username: appuser
    password: apppassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
